### ISSUE TITLE
EditPath.iss removes PathMgr.dll if uninstall was canceled

### ISSUE THREAD

**Issue by vadimgrn** [Bill-Stewart/PathMgr#2]
The result is that you can't uninstall the app next time because PathMgr.dll does not exist. Procedure DeinitializeUninstall() must delete PathMgr.dll only if uninstall was not canceled by user.

**Comment by Bill-Stewart** [comment]
Good catch, thank you.

Off the top of my head, one idea to fix this would be to set a global variable to `true` in the `CurUninstallStepChanged` event procedure if `CurUninstallStep = usUninstall`, and then check if this variable is `true` in the `DeinitializeUninstall` event procedure.

**Comment by vadimgrn** [comment]
https://stackoverflow.com/questions/2540173/running-an-application-at-the-end-of-the-uninstall-in-innosetup-handling-the-us

**Comment by Bill-Stewart** [comment]
Correction, we should check for the value `usPostUninstall` in `CurUninstallStepChanged` (rather than `usUninstall`) to determine if the global should be set to `true`. But otherwise I think this sounds right.

So at the top of the script we add a global:

```
var
  PathIsModified: Boolean;          // Cache task selection from previous installs
  ApplicationUninstalled: Boolean;  // Has application been uninstalled?
```

Initialize the global in `InitializeUninstall`:

```
function InitializeUninstall(): Boolean;
begin
  result := true;
  // Was task selected during a previous install?
  PathIsModified := GetPreviousData(MODIFY_PATH_TASK_NAME, '') = 'true';
  ApplicationUninstalled := false;
end;
```

Update `CurUninstallStepChanged` like this:

```
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    // Remove app directory from path during uninstall if task was selected;
    // use variable because we can't use WizardIsTaskSelected() at uninstall
    if PathIsModified then
      RemoveDirFromPath(ExpandConstant('{app}'));
  end
  else if CurUninstallStep = usPostUninstall then
  begin
    ApplicationUninstalled := true;
  end;
end;
```

And lastly, check the global in DeinitializeUninstall:

```
procedure DeinitializeUninstall();
begin
  if ApplicationUninstalled then
  begin
    // Unload and delete PathMgr.dll and remove app dir when uninstalling
    UnloadDLL(ExpandConstant('{app}\PathMgr.dll'));
    DeleteFile(ExpandConstant('{app}\PathMgr.dll'));
    RemoveDir(ExpandConstant('{app}'));
  end;
end;
```

I think that should do it.

**Comment by vadimgrn** [comment]
Thank you, now it works as expected.

**Comment by vadimgrn** [comment]
Fixed
